### ISSUE TITLE
[Bug]: "Only file and data URLs are supported by the default ESM loader" when running in Windows environment.

### ISSUE THREAD

**Issue by jlenon7** [japa/runner#10]
## Description

Hello guys. I have a [project](https://github.com/AthennaIO/Template) here in GitHub that is using ESM. Every commit to this project triggers a GitHub Actions CI pipeline that runs the Japa tests in Linux environment and then in Windows environment.

## Package version
2.0.7

## Error Message & Stack Trace

In Linux environment everything works well. But on Windows, I'm facing this error:

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/52840235/165881916-9fe810da-b787-4416-86a6-ba9c93f89c4f.png">

### Steps to reproduce

I think it is a little hard to reproduce this problem because it is happening only on Windows. But here is it:

1. Clone my project at: https://github.com/AthennaIO/Template
2. npm install
3. npm run test (The error comes up)

**Comment by thetutlage** [comment]
Please see this https://github.com/japa/core/issues/57#issuecomment-1079582007

**Comment by thetutlage** [comment]
Feel free to reopen with the mentioned resolution does not fix your issue
