### ISSUE TITLE
Adonis tests are failing when we setup application on different PC or location or after re-installing the dependencies.

### ISSUE THREAD

**Issue by iyashpal** [japa/runner#12]
## Description
I don't know if this is a bug or not but all tests are failing when I set up the adonis application on a different location or PC or in case I delete the `node_modules` directory and re-install the npm dependencies. At the moment, I found two issues :
1.  `route` from the test context is getting undefined.
2.  `loginAs` function is not working.

### Test 1
```javascript

  test('Need email|mobile & password to login.', async ({ client, route }) => {
    const response = await client.post(route('api.login')).accept('json')

    response.assertStatus(422)

    response.assert?.containsSubset(response.body(), {
      errors: [{ field: 'email' }, { field: 'password' }],
    })
  })
```

### Test 2
```javascript
test('An authenticated user can see the list of categories too.', async ({ client, assert }) => {
    const categories = await CategoryFactory.createMany(5)

    const user = await UserFactory.create()

    const response = await client.get('/api/categories').loginAs(user).accept('json')

    response.assertStatus(200)

    response.assert?.equal(5, response.body()?.length)

    assert.containsSubset(response.body(), categories.map(({ id, type, name }) => ({ id, type, name })))
  })
```

These tests were passing when I set up the fresh AdonisJS application but failed after re-installing dependencies/relocating by repo clone. I have attached two screenshots of the test results.

## Expected Behaviour
If `route` and `loginAs` functions were passing before push (Push to git repo) then it should be working when I clone the code and installl the dependencies in another location or PC.

## Steps to Reproduce
1. Install the fresh adonis application via commands.
4. Write some functional tests (just like above I mentioned). Tests should utilize the functions `route` from the test context  and `loginAs` in test suite body. Tests should be passing.
5. Delete `node_modules` directory OR move application files to the new location without `node_modules` directory and install dependencies via `yarn`
6. Run the test command `node ace test` and the above two test examples will fail.

## Package version
v2.0.7

## Error Message & Stack Trace
![image](https://user-images.githubusercontent.com/19922707/166208698-4068d7d6-be79-4ed5-b981-d7e9b665652b.png)

![image](https://user-images.githubusercontent.com/19922707/166209324-66465b30-e496-443c-8596-ffbb503a9f27.png)

**Comment by thetutlage** [comment]
Do you have `.env.test` file in the project root? If yes, what is the value of `SESSION_DRIVE` in it.

As a side note - We encourage everyone to use [Github discussions](https://github.com/adonisjs/core/discussions) and only use issues when something is confirmed as a verified bug

**Comment by iyashpal** [comment]
Okay, will create the discussion next time. Yes, I do have `.env.test` here is the content in it.

```.env
PORT=3334
HOST=0.0.0.0

NODE_ENV=development

APP_KEY=ILxcpFhAtxuEmQos7L0QF0qPui0FDn2N

DRIVE_DISK=local

SESSION_DRIVER=memory

CACHE_VIEWS=false


DB_CONNECTION=pg

PG_HOST=localhost
PG_PORT=5432
PG_USER=docker
PG_PASSWORD=secret
PG_DB_NAME=test_runner


SMTP_HOST=localhost
SMTP_PORT=587
SMTP_USERNAME=<username>
SMTP_PASSWORD=<password>
```

**Comment by iyashpal** [comment]
I have inspected this file:
```json
"testProviders": [
    "@japa/preset-adonis/TestsProvider"
  ]
```

and seems it's not getting execute.

**Comment by iyashpal** [comment]
This morning I moved the application to new location without `node_modules` after installation of npm dependencies tests getting failed. and all fails are due to `route` function and `loginAs` function. I have updated `@japa/preset-adonis/TestsProvider/index.js` with following code in both codebases `fresh-application` and `existing-application`. I am getting logs in `fresh-application` only.


```javascript
// @japa/preset-adonis/TestsProvider/index.js

"use strict";
/*
 * @japa/preset-adonis
 *
 * (c) Japa.dev
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * AdonisJS provider for registering japa class to the container
 */
class TestsProvider {
    constructor(app) {
        this.app = app;
    }
    register() {
        console.log('Tests Provider register call')

        this.app.container.bind('Japa/Preset/Test', () => {
            const { Test } = require('@japa/runner');
            return Test;
        });
        this.app.container.bind('Japa/Preset/TestContext', () => {
            const { TestContext } = require('@japa/runner');
            return TestContext;
        });
        this.app.container.bind('Japa/Preset/Assert', () => {
            const { Assert } = require('@japa/assert');
            return Assert;
        });
        this.app.container.bind('Japa/Preset/ApiClient', () => {
            const { ApiClient } = require('@japa/api-client');
            return ApiClient;
        });
        this.app.container.bind('Japa/Preset/ApiRequest', () => {
            const { ApiRequest } = require('@japa/api-client');
            return ApiRequest;
        });
        this.app.container.bind('Japa/Preset/ApiResponse', () => {
            const { ApiResponse } = require('@japa/api-client');
            return ApiResponse;
        });
    }
    boot() {
        console.log('Tests Provider boot call')
        this.app.container.withBindings(['Adonis/Core/Route', 'Japa/Preset/TestContext'], (Route, TestContext) => {
            TestContext.macro('route', function (routeIdentifier, params, options) {
                return Route.makeUrl(routeIdentifier, params, options);
            });
        });
    }
}
exports.default = TestsProvider;

```

**Comment by thetutlage** [comment]
Is the `TestProvider` registered inside the `.adonisrc.json` file in that old project? If possible please share your project as a repo for me reproduce the issue

**Comment by iyashpal** [comment]
Yes, it's registered there. I will invite you to the repo.

**Comment by iyashpal** [comment]
@thetutlage you must have received the invitation of the repo.

**Comment by thetutlage** [comment]
Just noticed that the `.env.test` file you shared has `NODE_ENV = development`. It should be set to test. That is the reason the "testProviders" are not loading

**Comment by iyashpal** [comment]
Okay, let me try it with test mode.

**Comment by iyashpal** [comment]
@thetutlage thank you so much for the help. You made my day. Closing the issue now.
