### ISSUE TITLE
Test runner breaks when `group` handler is `async`

### ISSUE THREAD

**Issue by ndianabasi** [japa/runner#16]
## Description

`Japa` seems not to support `async` handler current and breaks with the following unexpected behaviours:

1. All test running within the group with the `async` handler fails without any specific error,
2. Pinning all tests within the group with `group.tap((test) => test.pin())` results in all tests running (not just the tests within the `pinned` group).
3. Pinning only one tests within a group with the `async` handler runs few random tests with the pinned tests still failing.

## Package version

```text
    "@japa/api-client": "^1.2.0",
    "@japa/assert": "^1.3.4",
    "@japa/preset-adonis": "^1.0.15",
    "@japa/run-failed-tests": "^1.0.7",
    "@japa/runner": "^2.0.7",
```

## Error Message & Stack Trace

As seen below, the failed test was the only pinned test within a group with `async` handler but few other random tests ran while the pinned test still failed.

```bash
unit / Pagination Service (tests/unit/pagination_service.spec.ts)
  ✔ should return same pagination values if they are valid (1ms)
  ✔ should use `1` as `page` value if not provided (0ms)
  ✔ should use `20` as `per_page` value if not provided (0ms)
  ✔ should use `50` as `per_page` value if provided value is greater `50` (0ms)
{"level":30,"time":1653300409042,"pid":27492,"hostname":"Ndianabasi-Mac.lan","name":"backend-v1","msg":"started server on 0.0.0.0:4444"}

functional / Authentication (tests/functional/auth.spec.ts)
  ✔ User login should be successful (130ms)

tests/functional/workspace_users/update_users.spec.ts
  ✖ A superadmin can create and associate a user in any workspace (108ms)
```

## Relevant Information

Example of what I am trying to achieve with `async` group handler is generating a fake file only once for the all tests within a group:

```ts
test.group('Workspace Users | create', async (group) => {
  group.each.setup(async () => {
    await Database.beginGlobalTransaction()
    return () => Database.rollbackGlobalTransaction()
  })

  const role = () => faker.helpers.arrayElement(['designer', 'admin', 'manager'])
  const fakeAvatar = await file.generatePng('1mb')

  test('A superadmin can create and associate a user in any workspace', async ({
    assert,
    client: apiClient,
    route,
  }) => {

...

    const response = await apiClient
      .post(route('WorkspaceUsersController.store', [workspace.id]))
      .field('full_name', newUser.fullName)
      .field('email', newUser.email)
      .field('role', role())
      .file('avatar', fakeAvatar.contents, { filename: fakeAvatar.name })
      .loginAs(superadmin)

...

  })
})
```

**Comment by thetutlage** [comment]
Group handler isn't meant to be async. The code you are writing should be wrapped either inside a helper function or inside hooks

**Comment by thetutlage** [comment]
> Okay. Will there be any adverse implications of making Group handlers async?

It leads to the code I do not wish to write. The main goal of the group callback is to group tests and not run actions with top level code.

**Comment by ndianabasi** [comment]
Okay. I will be closing this.
