### ISSUE TITLE
Need HTML Test report

### ISSUE THREAD

**Issue by sulaimaan26** [japa/runner#18]
## Description

As of now we have only terminal reporting. It will be good if we implement HTML test report.
## Package version
2.0.8

**Comment by thetutlage** [comment]
I will leave this issue open for others to develop a plugin for HTML reporter

**Comment by Julien-R44** [comment]
@sulaimaan26 We already have one community package that generates HTML reports here : 
https://github.com/guntribam/table-driven-html-reporter
