### ISSUE TITLE
Trying to upload non-existing file hangs test suite

### ISSUE THREAD

**Issue by evoactivity** [japa/runner#25]
### Package version

2.2.1

### Describe the bug

When trying to upload a file that doesn't exist, the test runner hangs and never prints a summary or exits the process. This used up all my GitHub action minutes whilst I slept last night :(

```typescript
import { join } from "node:path";
import { test } from "@japa/runner";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

test.group("Service Provider Profile", async (group) => {
  // In my app I'm doing a database transaction
  // ------------------------------------------
  // group.each.setup(async () => {
  //   await Database.beginGlobalTransaction();
  //   return async () => await Database.rollbackGlobalTransaction();
  // });

  // but this is needed to trigger the hang
  // without this setup the hang does not occur
  // ------------------------------------------
  group.each.setup(async () => {
    await sleep(1);
    return async () => await sleep(1);
  });

  test("upload hangs", async ({ client }) => {
    await client
      .post(`/api/v1/upload`)
      .file("avatar", join(__dirname, "../does/not/exist/", "file.jpg"));
  });
});
```

There is a reproduction repo. Simply clone `npm install` and run `node ace test`.

### Reproduction repo

https://github.com/evoactivity/upload-hang-reproduction

**Comment by Julien-R44** [comment]
I don't have any problems on my side. I did `npm install`, then `node ace test` after filling my .env file.

Is there anything else to do? 

![image](https://user-images.githubusercontent.com/8337858/196567052-c3951f1c-a552-4e1f-9f61-079329799e99.png)

**Comment by evoactivity** [comment]
Hm, I wonder if this is different on windows. I'm on a mac and the github action runs on ubuntu.
I have a windows machine I can try and report back on.

**Comment by evoactivity** [comment]
I can't recreate on windows.

**Comment by Julien-R44** [comment]
Okay thanks for testing ! I'll dust off my old mac and give it a try asap

**Comment by evoactivity** [comment]
So I tried using [wtfnode](https://www.npmjs.com/package/wtfnode) to see what is keeping it alive, looks like something is using a stream/pipe but it wasn't too informative.

```
functional / Service Provider Profile (tests/functional/hello_world.spec.ts)
  ✔ display welcome page (224ms)
run
  ✔ upload doesn't hang (217ms)
  ✖ upload hangs (208ms)
  ✖ upload doesn't hang for full url (213ms)
^C[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Child processes
  - PID 10096
    - Entry point: node:internal/child_process:253
- Others:
  - Pipe
```

I've tried the latest minors of node 16 and 18.


If I comment out the `this.request.attach(...)` line for the `file` method the tests exit, so I thought the issue might be in superagent but it emits the error that the file doesn't exist as expected.
The `suite:end` event never seems to be emitted though.

If I use a full domain name eg

```typescript
test("upload doesn't hang for full url", async ({ client }) => {
  await client
    .post(`https://example.com/`)
    .file("avatar", join(__dirname, "/does/not/exist/", "file.jpg"));
});
```
It will exit as expected. If I use a relative url (whether or not it exists in routes.ts) it hangs.

I have managed to narrow down the issue to this function

```typescript
async runSetupCleanupFunctions() {
  console.log('runSetupCleanupFunctions this does log');
    try {
        await this.setupRunner.cleanup(this.hasError, this.suite);
        console.log('this never logs');
      }
      catch (error) {
        console.log('and neither does this');
        this.hasError = true;
        this.errors.push({ phase: 'setup:cleanup', error });
    }
}
```

If `await this.setupRunner.cleanup(this.hasError, this.suite);` is changed to `this.setupRunner.cleanup(this.hasError, this.suite);` it works. I don't know why.

Removing the cleanup code has no effect.
```ts
group.each.setup(async () => {
  await sleep(100);
  // return async () => await sleep(100);
});
```

Changing to `group.setup` the hang is fixed
```ts
group.setup(async () => {
  await sleep(100);
  return async () => await sleep(100);
});
```
