### ISSUE TITLE
Open APIs to get the current test/group and file name from a plugin

### ISSUE THREAD

**Issue by Julien-R44** [japa/runner#26]
Hey ! 

I started to take a quick look at writing a snapshot testing plugin for Japa.

I was quickly confronted with this problem. It seems to me that we have no API to retrieve the name of the test/group, as well as the name of the file currently executed.

I need this information to write a snapshot file next to the executed test file, and its content must include the name of the executed test.

I think we could have something quite similar to the [Tracker](https://github.com/japa/core/blob/develop/src/Tracker/index.ts) (or use this class but maybe split the "report summary generation" aspect into another class). 

What do you think about it? Do you have any better recommendations?

**Comment by thetutlage** [comment]
From where you want to access this info. Within the scope of the test?

**Comment by Julien-R44** [comment]
```ts
import type { PluginFn } from '@japa/runner'
import { expectTypeOf as expectType } from 'expect-type'
import { expectSnapshot } from './src'

export function snapshot(): PluginFn {
  return function (config, hey, { TestContext, Test, Group, Tracker }) {
     // Just here, in the plugin
    Tracker.currentGroup 
    Tracker.currentTest

    TestContext.macro('snapshot', expectSnapshot(config.cwd))
  }
}
```

Usage would be like : 
```ts
// my_test.spec.ts
import { test } from '@japa/runner'

test.group('My Group Name', () => {
	test('My Test Name', ({ snapshot }) => {
	   const obj = { foo: 'bar' }
	
	   snapshot.shouldMatch(obj)
	})
})
```

And so, the snapshot macro that is attached to the TestContext, when called, will retrieve the name of the file that is currently being tested, the name of the test etc. This will create a file like "my-test.snapshot.ts" next to the original file with the following content: 

```ts
// my_test.snapshot.ts
exports[`My Group Name > My Test Name`] = "snapshot content ...."
```

--- 

That means that the tracker, or whatever it is called, should provide the following information: 

- Current group name
- Current test name
- Current file name

Is it any clearer? Sorry, re-reading my first comment, it was indeed not.

**Comment by thetutlage** [comment]
Yup. It is clear now.

Since, you are in the `TestContext` scope, you can access all of this info as follows.

```ts
this.test // instance of test
this.test.parent // instance of group or undefined (for top level tests)
this.test.meta // this will have the filepath property
```

**Comment by Julien-R44** [comment]
Oooh it is already possible? Sorry, I didn't notice !
I'll look at it tonight and will close the issue

**Comment by Julien-R44** [comment]
Works great ! Thanks, I will look better next time 🙌

**Comment by juni0r** [comment]
I would be stoked by a snapshot plugin for Japa, @Julien-R44 . Using snapshots extensively in Jest, this of the few things I'm really missing from Japa. I'd be very interested in hearing about your progress and would certainly be an early adopter :)

**Comment by Julien-R44** [comment]
I have a little prototype that works but definitely lacks polish and features! I had to put it on pause but I hope to release the first version between mid-december 2022 and February 2023 ( because I'll be on vacation, so I'll have plenty of time to work on it 😋 )

**Comment by Julien-R44** [comment]
@juni0r a bit late, but here it is 😅
https://github.com/japa/snapshot

**Comment by juni0r** [comment]
@Julien-R44 That's fantastic, I'll give it a try soon. Thanks for letting me know! 🎉
