### ISSUE TITLE
Property 'expect' does not exist on type TextContext

### ISSUE THREAD

**Issue by derekr** [japa/runner#27]
### Package version

2.2.2

### Describe the bug

In VSCode the `expect` variable on `TextContext` is not defined as far as TS is concerned. Test works as expected in runtime.

It seems like when I have the `bin/test.ts` open in a split pane next to my spec file it can resolve the type OK, but if I just have the spec file open it shows the error and obviously no autocompletion or anything.

Might be a VSCode specific issue, but I'd assume it should be able to pick up the correct typing since I haven't seen any special setup instructions. Even when trying to add it to something like `japaTypes.ts` doesn't fix the issue, but also `expect` does exist on `TextContext` in that declaration.

![image](https://user-images.githubusercontent.com/22249/197580915-eb006c8d-74f1-477d-9967-0469a015d591.png)

![image](https://user-images.githubusercontent.com/22249/197581030-f5a7a147-fffa-41ed-a42f-b3d8b72dced7.png)

### Reproduction repo

https://github.com/derekr/japa-expect-ts-error

**Comment by Julien-R44** [comment]
Hey. Got the same issue with your repo, however, as soon as I add a tsconfig.json to the root ( even empty ), the error disappears :

![image](https://user-images.githubusercontent.com/8337858/197583803-a9efdc03-90dc-40eb-9602-4ea39b71744f.png)

I'm not sure why. But I'm tempted to say it's normal?

**Comment by derekr** [comment]
Ah ya know what. In my app I have my `bin/` dir next to my `src/` and tsconfig has `includes` specifying `src`. Including `bin/` fixes the issue and seems obvious in hindsight. Thanks for the quick reply!!
