### ISSUE TITLE
Bug with assertAgainstApiSpec on Adonisjs

### ISSUE THREAD

**Issue by bnoufel** [japa/runner#28]
### Package version

2.2.1

### Describe the bug

Hi,

I've a bug with using APIClient when i test a route API contains a slug `/admin/clients/:id`

![image](https://user-images.githubusercontent.com/6586577/197962636-728d584c-a4af-4f85-a5ef-273b948271e5.png)

On my OpenAPISchema i define also a route with slug like this
```
path:
    /admin/client/{id}:
```
or
```
path:
    /admin/client/:id:
```

But you can see on the screenshot, he don't find the route because he's search with the `id` not with the slug

Thank you

**Comment by thetutlage** [comment]
Please share the complete schema for this endpoint

**Comment by bnoufel** [comment]
yes sure
```
components:
  schemas:
    ClientSchema:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        email:
          type: string
        companyName:
          type: string
        sirenNumber:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        street:
          type: string
        zipCode:
          type: string
        city:
          type: string
        country:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/ClientSchema'
      required:
        - id
        - email
        - companyName
        - sirenNumber
        - lastName
        - firstName
        - street
        - zipCode
        - city
        - country
        - createdAt
        - updatedAt
        - files

paths:
  /admin/client/{id}:
    get:
      tags:
        - Admin
      summary: Get client
      description: ''
      responses:
        200:
          description: Get client information with company proof
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientWithCompanyProofSchema'
        '401':
          description: Not connected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '403':
          description: Forbidden access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
```

**Comment by thetutlage** [comment]
I suspect the `uuid` is breaking the OpenAPI parser we use. Can you please temporarily replace the `uuid` with a number value and see if it still breaks?

**Comment by bnoufel** [comment]
Yes sorry,

i have the same issue with issue with an number id on migration & Model :/
![image](https://user-images.githubusercontent.com/6586577/197982102-83b1fe52-66ba-4fab-ac72-a9264d3a0976.png)

**Comment by thetutlage** [comment]
Seems weird. Can you please reproduce this issue in a fresh project and share its repo with me?

**Comment by bnoufel** [comment]
Okay np, i give you the project soon ;)

**Comment by bnoufel** [comment]
Hi !,

I have a good and bad news 😅 

The good one, i found the problem with myself when i create the test project... i just forgot the "s" en `client` 🤦🏻‍♂️  ahaha so subtle.

But i have an another "bug" with `map` function juste test `x` language in "one" time for example, i have a "network error"  
you can found the test project here https://github.com/bnoufel/japa-bug (i invite you)


_ps: sorry again for the first problem :/_
