### ISSUE TITLE
Config `importer` function returns wrong path when using ESM loader

### ISSUE THREAD

**Issue by Melchyore** [japa/runner#29]
### Package version

2.2.2

### Describe the bug

Node.js versions 16.17.0 & 18.12.1

Hello!

I have an ESM project and I tried to integrate Japa to run tests. However, when I run this command
`node --loader=ts-node/esm bin/test.ts` I get the following error: 
```
Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'


     1  defer
       node_modules/.pnpm/ts-node@10.9.1_2ddbbb1508daf8c6199f587657236c9e/node_modules/ts-node/src/esm.ts:159

     2  entrypointFallback
       node_modules/.pnpm/ts-node@10.9.1_2ddbbb1508daf8c6199f587657236c9e/node_modules/ts-node/src/esm.ts:168

     3  anonymous
       node_modules/.pnpm/ts-node@10.9.1_2ddbbb1508daf8c6199f587657236c9e/node_modules/ts-node/src/esm.ts:202

       node_modules/.pnpm/ts-node@10.9.1_2ddbbb1508daf8c6199f587657236c9e/node_modules/ts-node/src/esm.ts:409

     5  resolve
       node_modules/.pnpm/ts-node@10.9.1_2ddbbb1508daf8c6199f587657236c9e/node_modules/ts-node/src/esm.ts:197
```

Same thing with tsx.

This is my `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "ESNext",
      "DOM"
    ],
    "module": "ESNext",
    "moduleResolution": "Node",
    "baseUrl": ".",
    "typeRoots": [
      "src/types"
    ],
    "outDir": "./dist",
    "isolatedModules": false,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "exclude": ["node_modules", "dist"],
  "ts-node": {
    "esm": true,
    "transpileOnly": true
  }
}
```

I have a simple test file:

```ts
import { test } from "@japa/runner";

import parsePolicy from "../src/parse_policy.js";

const policy = {
  "@context": "http://www.w3.org/ns/odrl.jsonld",
  "@type": "Set",
  uid: "http://example.com/policy:1010",
  permission: [
    {
      target: "http://example.com/asset:9898.movie",
      action: "use",
    },
  ],
};

test.group("Policy parser", () => {
  test("should parse ODRL policy", async ({ assert }) => {
    const parsedPolicy = await parsePolicy(JSON.stringify(policy));

    assert.lengthOf(parsedPolicy.permissions, 1);
  });
});
```

Thank you!

**Comment by Melchyore** [comment]
It seems that the `importer` function needs to return a path that starts with `file://` (I don't know if it's a bug or intended). Solution below:

```ts
configure({
  ...processCliArgs(process.argv.slice(2)),
  ...{
    files: ["tests/**/*.spec.ts"],
    plugins: [assert(), runFailedTests()],
    reporters: [specReporter()],
    importer: (filePath) => import(`file://${filePath}`), // ⬅ Here
  },
});
```

@thetutlage Can you please confirm whether it's a bug or not?

**Comment by thetutlage** [comment]
Not a bug, the same needs to be written inside in an ESM project manually. We are doing it on all AdonisJS packages too.

Maybe, the `create-japa` initializer can generate the right code for `bin/test.ts` file

**Comment by Melchyore** [comment]
> Not a bug, the same needs to be written inside in an ESM project manually. We are doing it on all AdonisJS packages too.
> 
> Maybe, the `create-japa` initializer can generate the right code for `bin/test.ts` file

Thank you. I think it's also a good idea to add a note about this here: https://japa.dev/docs/usage-with-typescript#esm-projects

**Comment by thetutlage** [comment]
Added option for a `TypeScript ESM` project in the `create-japa` package. https://github.com/japa/create-japa/commit/e05d09a72673368cbbf7de7e78b193ff5b6ad999
