### ISSUE TITLE
Can't use project's root folder in runner config

### ISSUE THREAD

**Issue by Daut** [japa/runner#32]
### Package version

4.0.0

### Describe the bug

Hi,

When I try to use project's root folder to set up runner config, I'm getting the following error

```
   ReferenceError: describe is not defined


   ⁃ Object.<anonymous>
     node_modules/json-schema-traverse/spec/index.spec.js:6
   ⁃ async importFiles
     node_modules/@japa/runner/build/index.js:151
```

My `bin/test.js` file looks like
```js
import { assert } from '@japa/assert'
import { pathToFileURL } from 'node:url'
import { apiClient } from '@japa/api-client'
import { specReporter } from '@japa/spec-reporter'
import { processCliArgs, configure, run } from '@japa/runner'

configure({
  ...processCliArgs(process.argv.slice(2)),
  ...{
    files: ['./**/*.spec.js'],
    plugins: [assert(), apiClient('http://localhost:3333')],
    reporters: [specReporter()],
    importer: (filePath) => import(pathToFileURL(filePath).href),
  },
})

run()
```

**Comment by thetutlage** [comment]
What is `describe`? Japa does not have any method called `describe`

**Comment by thetutlage** [comment]
Okay, I think I get it.

The error is coming from the `node_modules`, so it seems like the files glob is reading and importing files from node_modules as well.

I think, we will need a way to ignore certain directories. I will fix it

**Comment by thetutlage** [comment]
Fixed in https://github.com/japa/runner/releases/tag/v3.1.0
