### ISSUE TITLE
Missing type declaration for nested module import `@japa/runner/reporters`

### ISSUE THREAD

**Issue by OscarBarrett** [japa/runner#33]
### Package version

3.0.5

### Describe the bug

The [docs](https://japa.dev/docs/test-reporters#registering-and-activating-reporters) mention importing reporters from `@japa/runner/reporters`, but this nested module import does not seem to have a type declaration. Using the import still works however.

Example config

```ts
import { configure, processCLIArgs, run } from '@japa/runner';
import { spec } from '@japa/runner/reporters';

processCLIArgs(process.argv.slice(2));

configure({
  files: ['src/test/**/*.spec.ts'],
  reporters: {
    activated: ['spec'],
    list: [spec()],
  },
});

(async () => {
  await run();
})();
```

Shows an intellisense error `Cannot find module '@japa/runner/reporters' or its corresponding type declarations. ts(2307)`

**Comment by thetutlage** [comment]
Can you please the Node.js and the TypeScripts versions you are using?

**Comment by OscarBarrett** [comment]
Node v18.18.2 and Typescript 5.2.2

**Comment by Julien-R44** [comment]
Looking at your code, I see that you've wrapped the top level import in an IIFE

```ts
(async () => {
  await run();
})();
```

So I guess you're not using ESM. That's why your import isn't found. You'll need to set `compilerOptions.module" to "Node16" minimum

Japa is ESM-only library

**Comment by OscarBarrett** [comment]
Thanks, you're right - we're using ESM except for module resolution (`"module": "ESNext"`, `"moduleResolution": "node"` and `"type": "module"` in package.json).

Changing `moduleResolution` to `NodeNext` fixes this import.
