### ISSUE TITLE
Question: Including typings for plugins (i.e. assert)

### ISSUE THREAD

**Issue by malthe** [japa/runner#34]
### Package version

3.1.1

### Describe the bug

Given a test script like below, how should one best get the typings included for `TestContext` properties `assert` and `expect` which are [already declared](https://github.com/japa/assert/blob/develop/index.ts) in @japa/assert and @japa/expect.

```typescript
import { configure, processCLIArgs, run } from '@japa/runner';
import { assert } from '@japa/assert'
import { expect } from '@japa/expect';

processCLIArgs(process.argv.splice(2));

configure({
  files: ['tests/**/*.spec.ts'],
  plugins: [assert(), expect()],
});

run();
```
That is, how does one remove the red squiggly line under `assert` in the following test file:
```typescript
import { test } from '@japa/runner';
import type { TestContext } from '@japa/core';

function sum(a: number, b: number) {
  return a + b
}

test('add two numbers', ({ assert }: TestContext) => {
  assert.equal(sum(2, 2), 4)
})
```

**Comment by Julien-R44** [comment]
I guess this is a problem related to your tsconfig. Probably `moduleResolution` : it should be set to at least `Node16`

Otherwise, please share your tsconfig.json

**Comment by malthe** [comment]
This is my `tsconfig.json`:
```json
{
    "compilerOptions": {
        "moduleResolution": "node16",
        "target": "es2022",
        "module": "node16",
        "lib": [
            "es2019",
            "esnext.asynciterable",
            "esnext.bigint"
        ],
        "strict": true,
        "sourceMap": true,
        "inlineSourceMap": false,
        "declaration": true,
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "declarationDir": "dist",
        "allowImportingTsExtensions": true,
        "noEmit": true,
        "outDir": "dist"
    },
    "include": [
        "src",
        "tests"
    ]
}
```

**Comment by Julien-R44** [comment]
Thanks!
where is your test.ts file located? i'm talking about the file that contains this:

```ts
import { configure, processCLIArgs, run } from '@japa/runner' ;
import { assert } from '@japa/assert' ?
import { expect } from '@japa/expect' ;

processCLIArgs(process.argv.splice(2)) ;

configure({
  files : ['tests/**/*.spec.ts'],
  plugins : [assert(), expect()],
}) ;

run();
```

If you keep the default location, it should be in `./bin/test.ts`. And if this is the case, you need to include it in your `include` tsconfig : 

```ts
{
    "compilerOptions" : {
      // ....
    },
    "include" : [
        "bin", // Here 
        "src",
        "tests"
    ]
}
```

Otherwise, the module augmentation performed by importing @japa/assert will not be effective

**Comment by Julien-R44** [comment]
Did you tried restarting the typescript server / editor after updating that ? 

Otherwise, can you provide a reproduction repo please?

**Comment by malthe** [comment]
@Julien-R44 see https://github.com/malthe/japa-runner/tree/typing-issue – thanks!

**Comment by Julien-R44** [comment]
It works just fine for me dude : 
![image](https://github.com/japa/runner/assets/8337858/32bcb0ee-1ff7-44c7-a74c-811d6d6abaea)
![image](https://github.com/japa/runner/assets/8337858/90efc738-33fc-4942-aa24-60bef3b29610)

So yeah, i believe this was related to `include`.

**Comment by malthe** [comment]
I set up a workflow to run via GitHub Actions on that same repo.

Here's a run that demonstrates the error: https://github.com/malthe/japa-runner/actions/runs/7293525876/job/19876751955.

**Comment by Julien-R44** [comment]
You need to remove the `TestContext` annotation on this line : https://github.com/malthe/japa-runner/blob/1261dd00584b4594c2ac911297df71ff67be57a1/tests/math.test.ts#L8

You don't need it. This should works :
```ts
test('add two numbers', ({ assert }) => {
  assert.equal(sum(2, 2), 4)
})
```

 And, if ever you need it the augmented TestContext type, you should import it through `@japa/runner/core` not `@japa/core`

```ts
import type { TestContext } from '@japa/core';
```

**Comment by malthe** [comment]
Thanks – works beautifully 🎄
