### ISSUE TITLE
Plugin-augmented properties (e.g. assert) not available in Deno

### ISSUE THREAD

**Issue by malthe** [japa/runner#35]
### Package version

3.1.1

### Describe the bug

In Node.js, given a plugin configuration such as:
```typescript
configure({
  files: ['tests/**/*.test.ts'],
  plugins: [assert()],
});
```
The `TestContext` object is [augmented](https://github.com/japa/assert/blob/8fe6883035f7a19e0ba9775f5b4453bd71156d1e/index.ts#L34) with an "assert" property:
```typescript
TestContext.getter('assert', () => new Assert(), true)
```
However, when running the test script using Deno, the test context which is passed to the test function does not have this property – see [this failing test run](https://github.com/malthe/japa-runner/actions/runs/7298142472/job/19888581456).

When looking at the code, I see that @japa/assert uses `import { TestContext } from '@japa/runner/core'` while the code that's [creating the test context](https://github.com/japa/runner/blob/main/src/create_test.ts) uses `import { TestContext as BaseTestContext } from '@japa/core'`.

Somehow this works in Node.js but not in Deno – but why? I understand that Deno may not be a target runtime for Japa, but I came to Japa because [Jest](https://jestjs.io/) does not work in Deno (see [this issue](https://github.com/denoland/deno/issues/20619) which discusses some of the problems).

### Reproduction repo

https://github.com/malthe/japa-runner/tree/typing-issue

**Comment by thetutlage** [comment]
Does it have anything to do with Deno module system? As far as I know (from my back dated knowledge), Deno has its own module system and they add npm support on top later. So maybe, it is still not 100% feature proof?

The issue seems to be coming from re-exports, which should work, because having re-exports is not an alien approach.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
