### ISSUE TITLE
Consider adding snapshot `hint`

### ISSUE THREAD

**Issue by mrazauskas** [japa/runner#38]
### Package version

`next`

### Describe the bug

This is feature request, not a bug report (for some reason Feature Request temple does not work).

I was looking for a lighter testing framework for a CLI tool. Japa looks like a good candidate, because of snapshots and FS wrapper. Most of the test I have are e2e tests. The CLI tool runs in a spawned process and I snapshot stderr / stdout. (Also in many cases fixture files have to be written and clean up.)

A single test checks both stderr and stdout in separate snapshots. I was wondering if it would be possible to add snapshot `hint` similar to what Jest has: https://jestjs.io/docs/next/expect#tomatchsnapshotpropertymatchers-hint

```js
import { test } from "@japa/runner";

test("handles feature", async ({ assert }) => {
  const { exitCode, stderr, stdout } = await spawn(fixtureUrl, ["feature"]);

  assert.snapshot(normalizeOutput(stderr)).match("stderr"); //  <- hint could be used here
  assert.snapshot(normalizeOutput(stdout)).match({ hint: "stdout" }); //  <- might be even better to pass it as an option

  assert.equal(exitCode, 0);
});
```

**Comment by mrazauskas** [comment]
Another idea: implement  `.matchFile()` matcher (for example, it could be similar to [`jest-specific-snapshot`](https://github.com/igor-dv/jest-specific-snapshot)):

```ts
import { test } from "@japa/runner";

test("handles feature", async ({ assert }) => {
  const { exitCode, stderr, stdout } = await spawn(fixtureUrl, ["feature"]);

  assert.snapshot(normalizeOutput(stderr)).matchFile("feature-stderr.snap.txt");
  assert.snapshot(normalizeOutput(stdout)).matchFile("feature-stdout.snap.txt");

  assert.equal(exitCode, 0);
});
```

This could even better for my use case, because the output is plain text. There is no need to wrap it inside JavaScript exports. Would work for JSON, image or any other data format as well.

**Comment by thetutlage** [comment]
Hey, it seems like Jest will be a better fit for you right now. Since, you are looking for multiple features from Jest in Japa.

Of course, you can help implement the snapshots feature if you like. I do not have the bandwidth to implement these requests right away.

**Comment by mrazauskas** [comment]
Understandable. Thanks for quick response.
