### ISSUE TITLE
'npm init japa' fails with '@japa/browser-client'

### ISSUE THREAD

**Issue by JamesBurgoon** [japa/runner#39]
### Package version

japa@4.0.0

### Describe the bug

When doing a `npm init japa` command (docs: https://www.npmjs.com/package/create-japa), if `@japa/browser-client` plugin is selected, the initialization fails with a playwright error:
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: process.cwd()@0.0.0
npm ERR! Found: playwright@1.43.0-alpha-1709823751000
npm ERR! node_modules/playwright
npm ERR!   dev playwright@"1.43.0-alpha-1709823751000" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer playwright@"^1.38.1" from @japa/browser-client@2.0.0-4
npm ERR! node_modules/@japa/browser-client
npm ERR!   dev @japa/browser-client@"2.0.0-4" from the root project
```

**Comment by RomainLanz** [comment]
Hey @JamesBurgoon! 👋🏻 

It seems that you have installed an alpha version of `playwright` but `@japa/browser-client` requires `playwright@^1.38.1`.

**Comment by Julien-R44** [comment]
closing since no answer
