### ISSUE TITLE
"with" is executed before "setup" when running a test

### ISSUE THREAD

**Issue by guntribam** [japa/runner#4]
## Description

This is not a bug, i believe it is a more a discussion than a bug.

When running an functional test in japa my "with" function is executed before my test setup function.

Let me illustrate my use case:

i have the following test configuration:

```ts
import 'reflect-metadata'
import sourceMapSupport from 'source-map-support'
import execa from 'execa'
import { assert } from '@japa/assert'
import { specReporter } from '@japa/spec-reporter'
import { processCliArgs, configure, run } from '@japa/runner'
import { join } from 'path'
import type { HttpServer } from '@adonisjs/core/build/src/Ignitor/HttpServer'
import { Ignitor } from '@adonisjs/core/build/src/Ignitor'

sourceMapSupport.install({ handleUncaughtExceptions: false })

async function setupServer() {
  let server: HttpServer;
  try {
    server = new Ignitor(join(__dirname, '..')).httpServer()
    await server.start()
  } catch (error) {
    console.log("Erro ao subir o servidor de testes", error)
  }
  return async () => await server.close()
}

async function initTestBaseState() {
  const Database = (await import('@ioc:Adonis/Lucid/Database')).default;
  const { initCacheBaseState, resetCache } = (await import('Database/samples/SamplesUtils'));
  try {
    await execa.node('ace', ['migration:fresh', '--seed'], { stdio: 'inherit' });
    initCacheBaseState();
    await Database.beginGlobalTransaction()
  } catch (error) {
    console.log("Erro ao rodar migration:fresh", error)
  }
  return async () => {
    await Database.commitGlobalTransaction()
    resetCache();
  }
}

async function restoreTestBaseState() {
  const Database = (await import('@ioc:Adonis/Lucid/Database')).default;
  const { restoreCacheBaseState } = (await import('Database/samples/SamplesUtils'));
  await Database.rollbackGlobalTransaction()
  restoreCacheBaseState();
  await Database.beginGlobalTransaction()
}

configure({
  ...processCliArgs(process.argv.slice(2)),
  ...{
    suites: [
      {
        name: 'unit',
        files: ['japa/unit/**/*.fixture.ts'],
      },
      {
        name: 'acceptance',
        files: ['japa/acceptance/**/*.fixture.ts'],
        configure: (suite) => {
          suite.setup(initTestBaseState)
          suite.onTest(test => test.setup(restoreTestBaseState))
        }
      }
    ],
    setup: [setupServer],
    plugins: [assert()],
    reporters: [specReporter()],
    importer: (filePath) => import(filePath)
  },
})
run()
```
The order here -> it runs my `setupServer` function -> it runs my `configureSuite` function where i set the setup function of my funcional suite with `ìnitTestBaseState`, right here i delete, migrate and seed my database and begin a global transaction that is going to be rolled back after each functional test -> after that i set the setup function of each test to rollback to the initial state of the migration

The problem is that my `with` functions contains data that's inserted on the database. If the `with` is executed before, i lose the data on the rollback of the setup function.

Do you belive that is a good idea to run `setup` before `with` ?

## Package version
2.0.3

**Comment by thetutlage** [comment]
Yes, this is the expected workflow. The `with` methods returns the data which defines how many times the test should be executed. Whereas, the `setup` method runs before every test.

For example: If the `with` method returns an array with 10 items, then the setup method will also run for 10 times. Therefore, running `setup` before `with` is not possible.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
