### ISSUE TITLE
Type safety not working for test callback params props

### ISSUE THREAD

**Issue by bcastillo-2022474** [japa/runner#42]
### Package version

3.1.4

### Describe the bug

Hi, awesome library, but im having problems trying to set it up, I have this config:

```javascript
import { configure, processCLIArgs, run } from "@japa/runner";
import { expect } from "@japa/expect";
import { ApiClient, apiClient } from "@japa/api-client";
import dbConnection from "../src/db/db-connection.js";
import mongoose from "mongoose";
import { app } from "../routes.js";

ApiClient.setup(async () => {
  const connection = await dbConnection();

  // clean up the database before running the tests
  await Promise.all(
    Object.values(mongoose.connection.collections).map(async (collection) => {
      collection.deleteMany({});
    }),
  );

  return () => {
    connection.close();
  };
});

processCLIArgs(process.argv.splice(2));
configure({
  files: ["tests/**/*.spec.js"],
  plugins: [expect(), apiClient(`http://localhost:${process.env.PORT}`)],
  configureSuite(suite) {
    suite.setup(async () => {
      console.log("API suite setup");
      const server = app.listen(process.env.PORT, () => {
        console.log(`Server running at http://localhost:${process.env.PORT}`);
      });

      return () => {
        server.close();
      };
    });
  },
});

run();
```

and this test:

```javascript
import { test } from "@japa/runner";

test.group("Health check", () => {
  test("should return status code 200", async ({ expect, client }) => {
    const response = await client.get("/");
    console.log(response);

    expect(response.status()).toBe(200);
  });
});
```

and im unnable to get typesafety and intellisense working in the context params props (`expect` and `client`), like, it works kinda okay, and I if I run the test it works, but, is not showing any intellisense with expect and client apis and is really annoying, I tried searching the types of the library but couldn't find anything, and I think it is meant to work just like that, but Im unnable to get the types working. idk if there are no types, or if its some bug, but, I cant really work without them. is there some work around?

I dont have too much time to create a reproducible repo, but you can checkout current mine, in this commit `7fa0a7a`, the complete URL is [this](https://github.com/kinal-team-1/DAEM-backend/commit/7fa0a7a)

### Reproduction repo

https://github.com/kinal-team-1/DAEM-backend/commit/7fa0a7a

**Comment by RomainLanz** [comment]
Hey @bcastillo-2022474! 👋🏻 

It seems that you installed the "beta" version of our package. Could you try again with the latest release?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by imprakharshukla** [comment]
Hey! I am facing the same issue, I cannot get the types to work on the TestContext.

Packages:
"@japa/api-client": "2.0.3",
"@japa/expect": "3.0.2",
 "@japa/runner": "3.1.4",
