### ISSUE TITLE
Question - VS Code breakpoint Not Hit in Japa V2

### ISSUE THREAD

**Issue by nelsonjd** [japa/runner#44]
I used to be able to hit the VS Code debugger in old Japa and Adonis V5 using this command 
`node --inspect=9230 ace test`.  You also had to `Debug: Toggle Auto Attach` and select `Only With Flag`

We upgraded to Japa V2, still on Adonis V5 and this stopped working for me.  Any ideas on how to hit a breakpoint in the tests?

**Comment by pohy** [comment]
I am having the same issue.
