### ISSUE TITLE
Question - Is there any way to log the errors from the test?

### ISSUE THREAD

**Issue by lucasctd** [japa/runner#46]
I am using japa on a AdoniJS project but when my tests fail, it only shows it has failed but does not say where xD
If I want to see the logs I have to add a `try/catch` inside my test body and add a `console.log` inside the `catch `block to see what went wrong 😐
![image](https://github.com/user-attachments/assets/5110332b-6f0a-4e8f-8f14-74a0d1e75ffd)

**Comment by thetutlage** [comment]
Don't you get a list of errors after the tests summary? Can you please share complete screenshot of your terminal

**Comment by lucasctd** [comment]
![image](https://github.com/user-attachments/assets/5e07e7e2-7913-4a2c-be8d-2109f692a602)
No I don't get anything.

**Comment by thetutlage** [comment]
Seems weird. What version of `@japa/runner` are you using?

Also, is it possible for you to reproduce this error in a new app and share the repo with me?

**Comment by lucasctd** [comment]
I am using version 3.1.4.
I gonna install a clean version of AdonisJS and run a test to see what happens.
