### ISSUE TITLE
Discussion for a new feature - option to not decorate browser

### ISSUE THREAD

**Issue by jeppester** [japa/runner#47]
I'm going to introduce adonisjs to a team of devs as an alternative for rails for some of our projects.
The team consists of devs with various levels of experience, so it's important that I can make the experience as dev friendly as possible.

For that reason I'd like an option to not decorate the page api.
A "vanilla" playwright I feel will be less confusing and easier to find help for.

Why would I even use japa then?
Because japa does a really good job at launching the app for the playwright test suite, and making it possible to have the tests run in migrations. Great job on that part :+1: 

Would you accept a PR for making the change or is it out of scope?

**Comment by thetutlage** [comment]
May I know which part of decorating the browser is becoming an issue? Because, you still have all the APIs from Playwright, its just decorators allows for additional methods to the added (aka extend the existing objects)

**Comment by jeppester** [comment]
> May I know which part of decorating the browser is becoming an issue? Because, you still have all the APIs from Playwright, its just decorators allows for additional methods to the added (aka extend the existing objects)

My main concern is that the added functionality currently does not work as well as using Playwrights own expectations - because they lack the built-in waiting behaviour. If https://github.com/japa/browser-client/issues/1 gets solved it would help a lot.

On top of that I'm not sure that japa gains a lot from adding assertions on top of playwright. At least In my company it would be a better sell if it was just a great way to get "standard" playwright running in a well integrated way.

That there are things added on top of playwright will - again in my company - be a cause for concerns about lock-in, our devs ability to find help, adonis' longevity etc.

I do however completely understand if you prefer the browser test API to be more in line with the rest of japa - which is why I suggested a configuration option.

**Comment by thetutlage** [comment]
Since, the related PR has been merged. I think we can close this issue, because there is nothing actionable here. The decorators are just to extend the browser, context and the page and they are optional.

Lemme know if you still have any concerns and I can re-open this issue
