### ISSUE TITLE
Question - How can I test the call of a method with toHaveBeenCalled()?

### ISSUE THREAD

**Issue by diegormb06** [japa/runner#48]
When I tried to run the test with toHaveBeenCalled, I got an error saying that the argument must be a mock or a spy. How can I create a spy to test a method call?

the test function is:
```typescript
  test('updates a product', async ({ expect }) => {
    const updateData = { title: 'Updated Product' }
    mockProductRepository.update = async () => true

    const result = await productService.updateProduct(1, updateData)

    expect(result).toEqual(true)
    expect(mockProductRepository.update).toHaveBeenCalledWith(1, updateData)
  })
  ````

te error is: 
![image](https://github.com/user-attachments/assets/1a6688df-0f09-43c8-8bdb-9ae2cfc74db3)

**Comment by thetutlage** [comment]
Not sure if this is directory related to Japa, since the mocking capabilities are part of the `expect` library. However, how do you create the `mockProductRepository` object?

**Comment by diegormb06** [comment]
I just create a object with the methods, like I use to do with jest.

```javascript
const mockProductRepository = {
  getAll: async () => ({}) as Paginated<Product>,
  update: async () => true,
  delete: async () => true,
}
```
