### ISSUE TITLE
Typescript non-relative path class imports

### ISSUE THREAD

**Issue by akatora28** [japa/runner#7]
## Description

I'm trying to setup Japa to run typescript tests with ts-node into an existing Adonis v5.6.2 project. Setting up a basic test and importing classes from npm modules works fine. 

In my test I'm trying to test password hashing like the old Japa docs for Adonis. I would assume that the tsconfig.json files and presets will pull in the correct import paths, but that doesn't seem to be the case.

## Package version
2.0.6

## Error Message & Stack Trace

**test.spec.ts**
```ts
import { test } from '@japa/runner'
import User from 'App/Models/User';

test('ensure user password gets hashed during save', async ({assert}) => {
    const user = new User()
    user.email = "virk@adonisjs.com"
    user.password = "secret"
    await user.save()

    assert.notEqual(user.password, 'secret')
})
```

```bash
❯ npm run test

> [project]@1.0.0 test
> node -r ts-node/register/transpile-only bin/test.ts


   Cannot find module 'App/Models/User'
Require stack:
- /Users/[user]/[project]/tests/test.spec.ts
- /Users/[user]/[project]/bin/test.ts
  
   at Function.Module._resolveFilename internal/modules/cjs/loader.js:902
```

Updating the import User to a relative import works for importing the User model class, but fails at importing '@ioc:Adonis/Core/Hash'

```ts
import { test } from '@japa/runner'
import User from '../app/Models/User';

test('ensure user password gets hashed during save', async ({assert}) => {
    const user = new User()
    user.email = "virk@adonisjs.com"
    user.password = "secret"
    await user.save()

    assert.notEqual(user.password, 'secret')
})
```

```bash
❯ npm run test

> [project]@1.0.0 test
> node -r ts-node/register/transpile-only bin/test.ts


   Cannot find module '@ioc:Adonis/Core/Hash'
Require stack:
- /Users/[user]/[project]/app/Models/User.ts
- /Users/[user]/[project]/tests/test.spec.ts
- /Users/[user]/[project]/bin/test.ts
  
   at Function.Module._resolveFilename internal/modules/cjs/loader.js:902
```

**Comment by thetutlage** [comment]
That is because AdonisJS uses TypeScript transformers to convert aliases to relative path during the compile phase. Therefore, instead of using `ts-node`, you must use `@adonisjs/assembler`.

```sh
node -r @adonisjs/assembler/build/register bin/test.ts
```

**Comment by akatora28** [comment]
I updated to use the `@adonisjs/assembler` instead of `ts-node`, that seems to have helped some, but I'm running into a new error message now. Is that indicating TypeScript is still having issues accessing the IoC Container?

```bash
> [project]@1.0.0 test
> node -r @adonisjs/assembler/build/register bin/test.ts


   global[Symbol.for(...)] is not a function
  
   at Object.<anonymous> tests/user.spec.ts:2
    1|  import { test } from '@japa/runner'
  ❯ 2|  import User from 'App/Models/User';
    3|  
    4|  test('ensure user password gets hashed during save', async ({assert}) => {
    5|      const user = new User()
    6|      user.email = "virk@adonisjs.com"
    7|      user.password = "secret"
```

**Comment by thetutlage** [comment]
Are you booting the AdonisJS app? If you follow the cookbook on testing, you can find the instructions to boot the app https://docs.adonisjs.com/cookbooks/testing-adonisjs-apps#setup-for-adonisjs
